apiVersion: v1
kind: Service
metadata:
  name: back-end-service
spec:
  selector:
    app: back-end  # Matches the labels of the backend pods
  ports:
  - protocol: TCP
    port: 3000    # Service port
    targetPort: 3000 # Pod containerPort
  type: ClusterIP 