apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: thanhphan1098/k8s-review-user-service:latest  # Tên image Docker của bạn
        ports:
        - containerPort: 3001  # Cổng mà container sẽ nghe
        env:
        - name: ENDPOINT_USER_SERVICE  # Các biến môi trường (nếu cần)
          value: http://127.0.0.1:3001